name: Continuous Integration

on:
  - pull_request
  - push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - run: composer install
      - run: composer check-cs
      - run: composer static
      - run: composer test